# vim:ts=2:sw=2:et
version: 2

# -----------------------------------------------------------------------------------------------
defaults:

  - workflow_trigger_on_tags: &workflow_trigger_on_tags
      filters:
        tags:
          only: /.*/

  - workflow_ubuntu1810: &workflow_ubuntu1810
      <<: *workflow_trigger_on_tags
      requires:
        - build_ubuntu1810

  - setup_prerelease_commit_hash: &setup_prerelease_commit_hash
      name: Store commit hash and prerelease
      command: |
        if [ "$CIRCLE_BRANCH" = release -o -n "$CIRCLE_TAG" ]; then echo -n > prerelease.txt; else date -u +"nightly.%Y.%-m.%-d" > prerelease.txt; fi
        echo -n "$CIRCLE_SHA1" > commit_hash.txt

  - run_build: &run_build
      name: Build
      command: |
        set -ex
        if [ "$CIRCLE_BRANCH" = release -o -n "$CIRCLE_TAG" ]; then echo -n > prerelease.txt; else date -u +"nightly.%Y.%-m.%-d" > prerelease.txt; fi
        echo -n "$CIRCLE_SHA1" > commit_hash.txt
        mkdir -p build
        cd build
        [ -n "$COVERAGE" -a "$CIRCLE_BRANCH" != release -a -z "$CIRCLE_TAG" ] && CMAKE_OPTIONS="$CMAKE_OPTIONS -DCOVERAGE=ON"
        cmake .. -DCMAKE_BUILD_TYPE="Release" $CMAKE_OPTIONS -G "Unix Makefiles"
        make -j4

  - solc_artifact: &solc_artifact
      path: build/solc/solc
      destination: solc

  - all_artifacts: &all_artifacts
      root: build
      paths:
        - solc/solc
        - test/soltest
        - test/tools/solfuzzer

  - run_tests: &run_tests
      name: Tests
      command: ./.circleci/test.sh

  - test_steps: &test_steps
      - checkout
      - attach_workspace:
          at: build
      - run:
          name: soltest
          command: ./.circleci/soltest.sh
      - store_test_results:
          path: test_results/
      - store_artifacts:
          path: test_results/
          destination: test_results/

  - test_ubuntu1810: &test_ubuntu1810
      docker:
        - image: trapni/solc-buildpack-deps:ubuntu1810
      environment:
        EVM: byzantium
        OPTIMIZE: 0
      steps: *test_steps

# -----------------------------------------------------------------------------------------------
jobs:

  test_spelling:
    docker:
      - image: circleci/python:3.6
    environment:
      TERM: xterm
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run:
          name: Install dependencies
          command: |
            pip install --user codespell
      - run:
          name: Check spelling
          command: ~/.local/bin/codespell -S "*.enc,.git" -I ./scripts/codespell_whitelist.txt

  test_coding_style:
    docker:
      - image: buildpack-deps:bionic
    steps:
      - checkout
      - run:
          name: Check for trailing whitespace
          command: ./scripts/check_style.sh

  test_buglist:
    docker:
      - image: circleci/node
    environment:
      TERM: xterm
    steps:
      - checkout
      - run:
          name: JS deps
          command: |
            npm install download
            npm install JSONPath
            npm install mktemp
      - run:
          name: Test buglist
          command: ./test/buglistTests.js

  build_ubuntu1810:
    docker:
      - image: trapni/solc-buildpack-deps:ubuntu1810
    environment:
      COVERAGE: "ON"
    steps:
      - checkout
      - run: *run_build
      - store_artifacts: *solc_artifact
      - persist_to_workspace:
          root: build
          paths:
            - "*"

  build_archlinux:
    docker:
      - image: trapni/solc-buildpack-deps:archlinux
    environment:
      TERM: xterm
    steps:
      - checkout
      - run: *run_build
      - store_artifacts: *solc_artifact
      - persist_to_workspace:
          root: build
          paths:
            - solc/solc
            - test/soltest
            - test/tools/solfuzzer

  build_osx:
    macos:
      xcode: "10.0.0"
    environment:
      TERM: xterm
      CMAKE_OPTIONS: -DLLL=ON
    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: |
            brew unlink python
            brew install z3
            brew install boost
            brew install cmake
            brew install wget
            ./scripts/install_obsolete_jsoncpp_1_7_4.sh
      - run: *run_build
      - store_artifacts: *solc_artifact
      - persist_to_workspace: *all_artifacts

  build_docs:
    docker:
      - image: trapni/solc-buildpack-deps:ubuntu1810
    steps:
      - checkout
      - run: *setup_prerelease_commit_hash
      - run:
          name: Build documentation
          command: ./scripts/docs.sh
      - store_artifacts:
          path: docs/_build/html/
          destination: docs-html

  test_ubuntu1810_homestead:
    <<: *test_ubuntu1810
    environment:
      EVM: homestead
      OPTIMIZE: 0

  test_ubuntu1810_homestead_opt:
    <<: *test_ubuntu1810
    environment:
      EVM: homestead
      OPTIMIZE: 1

  test_ubuntu1810_byzantium:
    <<: *test_ubuntu1810
    environment:
      EVM: byzantium
      OPTIMIZE: 0

  test_ubuntu1810_byzantium_opt:
    <<: *test_ubuntu1810
    environment:
      EVM: byzantium
      OPTIMIZE: 1

  test_ubuntu1810_constantinople:
    <<: *test_ubuntu1810
    environment:
      EVM: constantinople
      OPTIMIZE: 0

  test_ubuntu1810_constantinople_opt:
    <<: *test_ubuntu1810
    environment:
      EVM: constantinople
      OPTIMIZE: 1

  test_ubuntu1810_petersburg:
    <<: *test_ubuntu1810
    environment:
      EVM: petersburg
      OPTIMIZE: 0

  test_ubuntu1810_petersburg_opt:
    <<: *test_ubuntu1810
    environment:
      EVM: petersburg
      OPTIMIZE: 1

workflows:
  version: 2

  build_all:
    jobs:
      - build_ubuntu1810: *workflow_trigger_on_tags
      - build_archlinux: *workflow_trigger_on_tags
      - build_osx: *workflow_trigger_on_tags
      - build_docs: *workflow_trigger_on_tags
      - test_spelling: *workflow_trigger_on_tags
      - test_coding_style: *workflow_trigger_on_tags
      - test_buglist: *workflow_trigger_on_tags
      - test_ubuntu1810_homestead: *workflow_ubuntu1810
      - test_ubuntu1810_homestead_opt: *workflow_ubuntu1810
      - test_ubuntu1810_byzantium: *workflow_ubuntu1810
      - test_ubuntu1810_byzantium_opt: *workflow_ubuntu1810
      - test_ubuntu1810_constantinople: *workflow_ubuntu1810
      - test_ubuntu1810_constantinople_opt: *workflow_ubuntu1810
      - test_ubuntu1810_petersburg: *workflow_ubuntu1810
      - test_ubuntu1810_petersburg_opt: *workflow_ubuntu1810

  # nightly:
  #   triggers:
  #     - schedule:
  #         cron: "0 0 * * *"
  #         filters:
  #           branches:
  #             only:
  #               - develop
  #   jobs:
